### ISSUE TITLE
API Deprecation warning

### ISSUE THREAD

**Issue by manuelbcd** [JupiterOne/graph-sysdig#22]
Hello team,

We noticed that we are receiving request to endpoints that are deprecated. We strongly recommend you to avoid using any URL with the `overview` subfolder as part of the path. 

FYI @zemberdotnet @austinkelleher 

Apologies for the inconvenience

Best,

**Comment by austinkelleher** [comment]
@manuelbcd Thanks a lot for reaching out! We are currently using that route for verifying authentication: https://github.com/JupiterOne/graph-sysdig/blob/f57f18959caa3c35850712ac8c6e6dc3dc96c706/src/client.ts#L51

Do you have any suggestions on a better API that can be used to verify auth?

**Comment by manuelbcd** [comment]
Hi @austinkelleher. Probably I'm not understanding 100% your use case or I'm missing something but you don't need to check the authentication since the Sysdig API works via Token in the request header.  I would omit any "2nd action" related to authentication check.   Feel free to reach out if you consider I'm not answering your question.

Best

**Comment by manuelbcd** [comment]
I can confirm that this request didn't happen anymore. Closing the issue. 
Thank you @austinkelleher
